In [67]:
import prosail
from prosail import spectral_lib
import numpy as np
import numpy.matlib
import numpy as np
from numpy.random import seed
from numpy.random import rand
import numpy.matlib
import matplotlib.pyplot as plt
import pandas as pd

In [79]:
krange = 1000
n = 1.5 #Leaf structure parameter
chloro = rand(krange)*80 #Chlorophyll a+b concentration
caroten = caroten=rand(krange)*8 #Carotenoid concentration

brown = 0.0 #Brown pigment
EWT = 0.0005+rand(krange)*0.0695 #Equivalent water thickiness
LMA = 0.003+rand(krange)*0.005 #Dry matter content
LAI = rand(krange)*8 #Leaf Area Index
lidfa = -0.35 #Leaf angle distribution
hspot = 0.01 #Hotspot parameter
#tts = 30.0 #Solar zenith angle
#solar_zenith=numpy.matlib.repmat(np.arange(25,75,10),2,1).T.flatten()
tto = 10.0 #Observer zenith angle
psi = 0.0 #Relative sensor-solar azimuth angle 
typelidf=1 #Leaf angle distribution type
lidfb=-0.15 #Leaf angle distribution
rsoil=1.0 #Soil brigthness factor
psoil=1.0 #Dry/Wet soil factor
factor="DHR"


In [78]:
for i in np.arange(krange):
    rr = prosail.run_prosail(n, chloro[i], caroten[i], brown, EWT[i], LMA[i], LAI[i], lidfa, hspot,
                        tts, tto, psi, typelidf=1, lidfb=-0.15, 
                        rsoil = 1., psoil=1., factor="DHR")
    print(rr)
rr.save_csv(......)

[0.07287552 0.0727525  0.0726311  ... 0.13426924 0.13405501 0.13397053]
[0.0098779  0.0098532  0.00983831 ... 0.00598702 0.00599254 0.00599604]
[0.00984906 0.00985496 0.00985824 ... 0.00580011 0.00579382 0.00579464]
[0.11789326 0.11770571 0.1175157  ... 0.22047102 0.22018652 0.22003174]
[0.01118469 0.01112163 0.01106628 ... 0.00777774 0.00778015 0.00778212]
[0.00821391 0.00823078 0.00824429 ... 0.01177512 0.01166954 0.01171328]
[0.01410937 0.01410796 0.01410397 ... 0.0142303  0.0142246  0.01422123]
[0.00976378 0.00977723 0.00978789 ... 0.00589136 0.00589339 0.00589574]
[0.011215   0.01148427 0.01177809 ... 0.00502756 0.00503055 0.00503355]
[0.00860654 0.00861202 0.00862448 ... 0.00373716 0.0037211  0.00373194]
[0.12586397 0.12565242 0.12544071 ... 0.23507658 0.23479237 0.23461929]
[0.00813337 0.00815461 0.00817309 ... 0.00284101 0.00285016 0.00285668]
[0.16769568 0.16738874 0.1670791  ... 0.30931766 0.30904156 0.30883561]
[0.00864814 0.00866163 0.0086719  ... 0.00365991 0.00366853 0.00

In [50]:
help(prosail.run_prosail)

Help on function run_prosail in module prosail.sail_model:

run_prosail(n, cab, car, cbrown, cw, cm, lai, lidfa, hspot, tts, tto, psi, ant=0.0, alpha=40.0, prospect_version='5', typelidf=2, lidfb=0.0, factor='SDR', rsoil0=None, rsoil=None, psoil=None, soil_spectrum1=None, soil_spectrum2=None)
    Run the PROSPECT_5B and SAILh radiative transfer models. The soil
    model is a linear mixture model, where two spectra are combined together as
    
         rho_soil = rsoil*(psoil*soil_spectrum1+(1-psoil)*soil_spectrum2)
    By default, ``soil_spectrum1`` is a dry soil, and ``soil_spectrum2`` is a
    wet soil, so in that case, ``psoil`` is a surface soil moisture parameter.
    ``rsoil`` is a  soil brightness term. You can provide one or the two
    soil spectra if you want.  The soil spectra must be defined
    between 400 and 2500 nm with 1nm spacing.
    
    Parameters
    ----------
    n: float
        Leaf layers
    cab: float
        leaf chlorophyll concentration
    car: float
